export type Rarity = "common" | "uncommon" | "rare" | "very-rare";
export type AnimalType = "mammal" | "bird" | "reptile" | "amphibian" | "insect" | "fish";

export interface Animal {
  id: string;
  number: string;
  name: string;
  emoji: string;
  type: AnimalType;
  region: string;
  rarity: Rarity;
  description: string;
  unlocked: boolean;
  caughtLocation?: string;
}

export const animals: Animal[] = [
  {
    id: "red-fox",
    number: "001",
    name: "Red Fox",
    emoji: "🦊",
    type: "mammal",
    region: "Forest",
    rarity: "rare",
    description:
      "Known for its cunning nature and fiery coat, this agile creature thrives in dense woodlands. It uses its bushy tail for balance and warmth during chilly nights.",
    unlocked: true,
    caughtLocation: "Urban Wilds",
  },
  {
    id: "sparrow",
    number: "002",
    name: "Sparrow",
    emoji: "🐦",
    type: "bird",
    region: "Urban",
    rarity: "common",
    description:
      "A tiny but bold city dweller found perching on fences and ledges. Sparrows are social birds that chirp in cheerful flocks from dawn to dusk.",
    unlocked: true,
    caughtLocation: "City Park",
  },
  {
    id: "squirrel",
    number: "003",
    name: "Squirrel",
    emoji: "🐿️",
    type: "mammal",
    region: "Urban",
    rarity: "common",
    description:
      "A nimble acrobat of the treetops, always busy stashing acorns for winter. Its bushy tail acts as both a parachute and a blanket on cold nights.",
    unlocked: true,
    caughtLocation: "Riverside Park",
  },
  {
    id: "pigeon",
    number: "004",
    name: "Pigeon",
    emoji: "🕊️",
    type: "bird",
    region: "Urban",
    rarity: "common",
    description:
      "The original city bird. Pigeons have an uncanny sense of direction and have served as messengers for thousands of years. Don't underestimate them.",
    unlocked: true,
    caughtLocation: "Downtown Plaza",
  },
  {
    id: "raccoon",
    number: "005",
    name: "Raccoon",
    emoji: "🦝",
    type: "mammal",
    region: "Urban",
    rarity: "uncommon",
    description:
      "This masked bandit raids trash cans and dumpsters with surprising dexterity. Its nimble paws can unlatch containers and even turn doorknobs.",
    unlocked: true,
    caughtLocation: "Back Alley",
  },
  {
    id: "deer",
    number: "006",
    name: "White-Tail Deer",
    emoji: "🦌",
    type: "mammal",
    region: "Forest",
    rarity: "uncommon",
    description:
      "Graceful and alert, the white-tailed deer flashes its namesake tail as a warning signal when startled. Bucks grow new antlers each year.",
    unlocked: true,
    caughtLocation: "Forest Edge",
  },
  {
    id: "owl",
    number: "007",
    name: "Great Horned Owl",
    emoji: "🦉",
    type: "bird",
    region: "Forest",
    rarity: "rare",
    description:
      "A silent hunter of the night with rotating neck and razor-sharp talons. Its deep hoot echoes through dark forests, striking fear into small creatures.",
    unlocked: true,
    caughtLocation: "Old Oak Grove",
  },
  {
    id: "rabbit",
    number: "008",
    name: "Cottontail Rabbit",
    emoji: "🐇",
    type: "mammal",
    region: "Meadow",
    rarity: "common",
    description:
      "A fluffy sprinter that can reach 18 mph to escape predators. The white puff of its tail bobbles as it zigzags through tall grass.",
    unlocked: true,
    caughtLocation: "Clover Meadow",
  },
  {
    id: "duck",
    number: "009",
    name: "Mallard Duck",
    emoji: "🦆",
    type: "bird",
    region: "Wetland",
    rarity: "common",
    description:
      "The iridescent green head of the male mallard shimmers like spilled oil in sunlight. They are dabbling ducks, tipping tail-up to feed underwater.",
    unlocked: true,
    caughtLocation: "Mill Pond",
  },
  {
    id: "hedgehog",
    number: "010",
    name: "Hedgehog",
    emoji: "🦔",
    type: "mammal",
    region: "Meadow",
    rarity: "uncommon",
    description:
      "Armed with over 5,000 spines and a talent for rolling into a perfect ball, this tiny tank snuffles through gardens searching for beetles and worms.",
    unlocked: true,
    caughtLocation: "Garden Path",
  },
  {
    id: "butterfly",
    number: "011",
    name: "Monarch Butterfly",
    emoji: "🦋",
    type: "insect",
    region: "Meadow",
    rarity: "rare",
    description:
      "These living stained-glass windows migrate thousands of miles each year. Their wings are dusted with microscopic scales that scatter light into brilliant orange.",
    unlocked: true,
    caughtLocation: "Wildflower Field",
  },
  {
    id: "frog",
    number: "012",
    name: "Tree Frog",
    emoji: "🐸",
    type: "amphibian",
    region: "Wetland",
    rarity: "very-rare",
    description:
      "Sticky toe pads let this tiny climber scale glass windows. Their evening chorus near ponds is one of summer's most unmistakable sounds.",
    unlocked: true,
    caughtLocation: "Pond Shore",
  },
  {
    id: "bat",
    number: "013",
    name: "???",
    emoji: "🦇",
    type: "mammal",
    region: "Forest",
    rarity: "uncommon",
    description: "",
    unlocked: false,
  },
  {
    id: "snake",
    number: "014",
    name: "???",
    emoji: "🐍",
    type: "reptile",
    region: "Forest",
    rarity: "uncommon",
    description: "",
    unlocked: false,
  },
  {
    id: "heron",
    number: "015",
    name: "???",
    emoji: "🕊️",
    type: "bird",
    region: "Wetland",
    rarity: "rare",
    description: "",
    unlocked: false,
  },
  {
    id: "coyote",
    number: "016",
    name: "???",
    emoji: "🐺",
    type: "mammal",
    region: "Urban",
    rarity: "rare",
    description: "",
    unlocked: false,
  },
  {
    id: "salamander",
    number: "017",
    name: "???",
    emoji: "🦎",
    type: "amphibian",
    region: "Wetland",
    rarity: "very-rare",
    description: "",
    unlocked: false,
  },
  {
    id: "hawk",
    number: "018",
    name: "???",
    emoji: "🦅",
    type: "bird",
    region: "Highland",
    rarity: "rare",
    description: "",
    unlocked: false,
  },
  {
    id: "mole",
    number: "019",
    name: "???",
    emoji: "🦦",
    type: "mammal",
    region: "Meadow",
    rarity: "uncommon",
    description: "",
    unlocked: false,
  },
  {
    id: "dragonfly",
    number: "020",
    name: "???",
    emoji: "🐉",
    type: "insect",
    region: "Wetland",
    rarity: "uncommon",
    description: "",
    unlocked: false,
  },
  {
    id: "tortoise",
    number: "021",
    name: "???",
    emoji: "🐢",
    type: "reptile",
    region: "Meadow",
    rarity: "rare",
    description: "",
    unlocked: false,
  },
  {
    id: "weasel",
    number: "022",
    name: "???",
    emoji: "🦦",
    type: "mammal",
    region: "Forest",
    rarity: "very-rare",
    description: "",
    unlocked: false,
  },
  {
    id: "kingfisher",
    number: "023",
    name: "???",
    emoji: "🐦",
    type: "bird",
    region: "Wetland",
    rarity: "very-rare",
    description: "",
    unlocked: false,
  },
  {
    id: "porcupine",
    number: "024",
    name: "???",
    emoji: "🦔",
    type: "mammal",
    region: "Forest",
    rarity: "very-rare",
    description: "",
    unlocked: false,
  },
];

export const unlockedAnimals = animals.filter((a) => a.unlocked);

export const rarityColors: Record<Rarity, string> = {
  common: "bg-secondary-container",
  uncommon: "bg-primary-container",
  rare: "bg-tertiary-container",
  "very-rare": "bg-error-container",
};

export const rarityLabels: Record<Rarity, string> = {
  common: "COMMON",
  uncommon: "UNCOMMON",
  rare: "RARE",
  "very-rare": "VERY RARE",
};
