// AUTO-GENERATED by scripts/generate-sprites.mjs — do not edit.
// Run `npm run sprites` after changing scripts/sprites/data/.
export const SPRITE_DEX: ReadonlySet<number> = new Set<number>([1, 2, 3, 5, 9, 12, 13, 14, 15, 16, 49, 52, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76]);
