/**
 * Generates public/sprites/NNN.svg (+ NNN-s.svg silhouettes) and
 * src/lib/sprite-manifest.ts from the pixel grids in scripts/sprites/data/.
 *
 * Usage: npm run sprites
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { sprites } from "./sprites/index.mjs";
import { C, ramps } from "./sprites/palette.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT_DIR = join(ROOT, "public", "sprites");
const MANIFEST = join(ROOT, "src", "lib", "sprite-manifest.ts");

const SIZE = 24;
const SILHOUETTE_FILL = "#3c423f";

const sharedColors = new Set([
  ...Object.values(C),
  ...Object.values(ramps).flat(),
]);

function pad(n) {
  return String(n).padStart(3, "0");
}

function validate(sprite) {
  const { dex, name, palette, localColors = [] } = sprite;
  let { grid } = sprite;
  const fail = (msg) => {
    throw new Error(`Sprite #${dex} ${name}: ${msg}`);
  };
  if (!Number.isInteger(dex) || dex < 1) fail("invalid dex number");
  if (grid.length !== SIZE) fail(`grid has ${grid.length} rows, want ${SIZE}`);
  // Trailing transparent pixels may be omitted in the data files.
  sprite.grid = grid = grid.map((row) => row.padEnd(SIZE, "."));
  grid.forEach((row, y) => {
    if (row.length !== SIZE)
      fail(`row ${y} has ${row.length} chars, max ${SIZE}: "${row}"`);
    for (let x = 0; x < SIZE; x++) {
      const ch = row[x];
      if (ch !== "." && !(ch in palette))
        fail(`unknown char "${ch}" at row ${y} col ${x}`);
    }
  });
  const allowed = new Set(localColors);
  for (const [ch, hex] of Object.entries(palette)) {
    if (!sharedColors.has(hex) && !allowed.has(hex))
      console.warn(
        `  warn: #${dex} ${name}: char "${ch}" uses ${hex}, not in shared palette`
      );
  }
}

/** Merge each row into same-color runs, then group runs by color. */
function colorRuns(grid, palette) {
  const byColor = new Map();
  for (let y = 0; y < SIZE; y++) {
    const row = grid[y];
    let x = 0;
    while (x < SIZE) {
      const ch = row[x];
      if (ch === ".") {
        x++;
        continue;
      }
      let end = x + 1;
      while (end < SIZE && row[end] === ch) end++;
      const color = palette[ch];
      if (!byColor.has(color)) byColor.set(color, []);
      byColor.get(color).push([x, y, end - x]);
      x = end;
    }
  }
  return byColor;
}

function runsToPath(runs) {
  return runs.map(([x, y, w]) => `M${x} ${y}h${w}v1h-${w}z`).join("");
}

function svg(body) {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${SIZE} ${SIZE}" shape-rendering="crispEdges">${body}</svg>\n`;
}

function spriteSvg(sprite) {
  const paths = [];
  for (const [color, runs] of colorRuns(sprite.grid, sprite.palette)) {
    paths.push(`<path fill="${color}" d="${runsToPath(runs)}"/>`);
  }
  return svg(paths.join(""));
}

function silhouetteSvg(sprite) {
  const runs = [];
  for (let y = 0; y < SIZE; y++) {
    const row = sprite.grid[y];
    let x = 0;
    while (x < SIZE) {
      if (row[x] === ".") {
        x++;
        continue;
      }
      let end = x + 1;
      while (end < SIZE && row[end] !== ".") end++;
      runs.push([x, y, end - x]);
      x = end;
    }
  }
  return svg(`<path fill="${SILHOUETTE_FILL}" d="${runsToPath(runs)}"/>`);
}

function writeWithRetry(path, content) {
  // OneDrive can transiently lock files mid-sync; one retry is enough in practice.
  try {
    writeFileSync(path, content);
  } catch (err) {
    if (err.code === "EBUSY" || err.code === "EPERM") {
      writeFileSync(path, content);
    } else {
      throw err;
    }
  }
}

// ── main ──
const seen = new Set();
for (const sprite of sprites) {
  validate(sprite);
  if (seen.has(sprite.dex))
    throw new Error(`Duplicate dex number ${sprite.dex}`);
  seen.add(sprite.dex);
}

mkdirSync(OUT_DIR, { recursive: true });
for (const sprite of sprites) {
  writeWithRetry(join(OUT_DIR, `${pad(sprite.dex)}.svg`), spriteSvg(sprite));
  writeWithRetry(
    join(OUT_DIR, `${pad(sprite.dex)}-s.svg`),
    silhouetteSvg(sprite)
  );
}

const dexList = sprites
  .map((s) => s.dex)
  .sort((a, b) => a - b)
  .join(", ");
writeWithRetry(
  MANIFEST,
  `// AUTO-GENERATED by scripts/generate-sprites.mjs — do not edit.\n` +
    `// Run \`npm run sprites\` after changing scripts/sprites/data/.\n` +
    `export const SPRITE_DEX: ReadonlySet<number> = new Set<number>([${dexList}]);\n`
);

console.log(
  `Generated ${sprites.length} sprites (+ silhouettes) → public/sprites/, manifest → src/lib/sprite-manifest.ts`
);
