
UPDATE species SET description = CASE dex_number
  WHEN 13 THEN 'The national bird of the United States, soaring over mountains and rivers with a wingspan that commands the sky.'
  WHEN 14 THEN 'A forest generalist and strong swimmer, surprisingly fast despite its bulk. More curious than dangerous unless provoked.'
  WHEN 15 THEN 'Famous for its annual migration of thousands of miles. The orange and black wings are a warning to predators — it feeds on toxic milkweed.'
  WHEN 16 THEN 'An apex ambush predator that has survived virtually unchanged for millions of years. Thrives in warm freshwater swamps and marshes.'
  WHEN 17 THEN 'The largest cat in the Americas, built for power not speed. Jaguars crush prey with the strongest bite of any big cat relative to size.'
  WHEN 18 THEN 'Its oversized bill is lighter than it looks, mostly hollow inside. Uses bright colours to communicate with others in the canopy.'
  WHEN 19 THEN 'The world''s largest rodent. Highly social and semi-aquatic, capybaras are remarkably calm around other species, including humans.'
  WHEN 20 THEN 'One of the heaviest snakes on Earth, capable of subduing prey far larger than itself by constriction in dense waterways.'
  WHEN 21 THEN 'Its brilliant iridescent wings scatter light through microscopic scales rather than pigment — a structural colour trick unique in nature.'
  WHEN 22 THEN 'Uses its powerful claws to tear open termite mounds, consuming tens of thousands of insects daily with a long sticky tongue.'
  WHEN 23 THEN 'Tiny but deadly — its vivid colours advertise skin toxins strong enough to deter most predators. Safe to observe, dangerous to handle.'
  WHEN 24 THEN 'Europe''s largest native deer, the stag''s antlers are shed and regrown each year, growing heavier with age.'
  WHEN 25 THEN 'Hunts in near-total darkness using asymmetric ear placement to triangulate the exact position of prey beneath snow or grass.'
  WHEN 26 THEN 'A powerful digger that creates complex underground setts used by multiple generations. Badger clans are fiercely territorial.'
  WHEN 27 THEN 'One of Europe''s most vividly coloured birds, a flash of electric blue and orange along riverbanks. Dives with precision for small fish.'
  WHEN 28 THEN 'Intelligent and adaptable, wild boars use their disc-shaped snout to root through soil. They can cause significant ecological disruption.'
  WHEN 29 THEN 'Earth''s largest land animal, with a complex social memory and deep family bonds. Elephants mourn their dead and recognise themselves in mirrors.'
  WHEN 30 THEN 'The only truly social big cat, lions live in prides where females do most of the hunting. A male''s roar carries up to 8 kilometres.'
  WHEN 31 THEN 'The tallest animal alive, using its long neck to browse treetops other herbivores cannot reach. Its spots are as unique as fingerprints.'
  WHEN 32 THEN 'No two zebras share the same stripe pattern. The bold markings may confuse predators when the herd moves as one.'
  WHEN 33 THEN 'The fastest land animal on Earth, reaching 120 km/h in short bursts. Unlike other big cats, it cannot roar — it chirps and purrs.'
  WHEN 34 THEN 'One of our closest living relatives, sharing over 98% of human DNA. Found only in a small mountain range shared by Rwanda, Uganda, and DRC.'
  WHEN 35 THEN 'Gets its pink colouring entirely from the carotenoid pigments in the algae and crustaceans it filters from the water.'
  WHEN 36 THEN 'Africa''s largest freshwater predator. Patient and explosive — capable of outrunning a human over short distances on land.'
  WHEN 37 THEN 'Spends up to 16 hours a day eating bamboo to sustain its large body, despite having a carnivore''s digestive system ill-suited for plants.'
  WHEN 38 THEN 'A master of camouflage in rocky mountain terrain. The snow leopard''s range is vast but its secretive nature makes sightings extraordinarily rare.'
  WHEN 39 THEN 'A solitary apex predator of dense jungle. Each tiger''s stripe pattern is unique — used like a fingerprint for individual identification.'
  WHEN 40 THEN 'The world''s largest living lizard, using venom and bacteria in its bite to weaken prey. Can smell carrion from up to 9 kilometres away.'
  WHEN 41 THEN 'A sacred symbol in East Asian culture, this elegant crane performs elaborate courtship dances and mates for life.'
  WHEN 42 THEN 'Smaller and more forest-adapted than its African cousin. Highly intelligent, with documented tool use and strong social bonds.'
  WHEN 43 THEN 'Spends almost its entire life in the rainforest canopy, using its extraordinarily long arms to brachiate between trees with ease.'
  WHEN 44 THEN 'Moves by hopping at speeds up to 70 km/h. A female''s pouch can carry a joey for months after birth as it continues to develop.'
  WHEN 45 THEN 'Sleeps up to 22 hours a day, conserving energy from a low-nutrient eucalyptus diet that would be toxic to most other mammals.'
  WHEN 46 THEN 'One of the most unusual mammals on Earth — egg-laying, venomous, and using electroreception to detect prey underwater with its bill.'
  WHEN 47 THEN 'Its call sounds unmistakably like human laughter. The kookaburra uses this to mark territory at dawn and dusk each day.'
  WHEN 48 THEN 'The largest reptile on Earth. Equally at home in salt water and fresh, it has been recorded far out at sea between islands.'
  WHEN 49 THEN 'Despite its ferocious reputation, the Tasmanian devil is simply a very loud scavenger. Its powerful jaws can crush bone entirely.'
  WHEN 50 THEN 'A flightless bird capable of killing with a single kick. The cassowary''s casque-topped head and dagger-like claws make it deeply dangerous.'
  WHEN 51 THEN 'An apex marine predator with serrated teeth and electroreceptors that detect the heartbeat of prey hidden in sand.'
  WHEN 52 THEN 'The largest animal ever known to have existed. A blue whale''s heart is the size of a small car and audible from kilometres away.'
  WHEN 53 THEN 'Navigates thousands of miles of open ocean using the Earth''s magnetic field, returning to the exact beach where it was born to nest.'
  WHEN 54 THEN 'Lives in a symbiotic relationship with sea anemones, protected by a mucus coat that neutralises the stinging cells.'
  WHEN 55 THEN 'The ocean''s apex predator. Orcas live in matrilineal pods with distinct dialects, and coordinate hunts with sophisticated strategies.'
  WHEN 56 THEN 'The males'' impressive horn-like protrusions are used in combat for territory and mates. Despite its fearsome appearance, it is harmless to humans.'
  WHEN 57 THEN 'One of the heaviest insects on Earth. Males use their enormous horns to fight rivals and flip them off branches in the rainforest canopy.'
  ELSE description
END
WHERE dex_number BETWEEN 13 AND 57;
