
insert into public.quests (id, name, description, tier, required_dex_numbers, reward_badge_id, unlock_after_quest_id, order_index) values
  ('first_tracks',
   'First Tracks',
   'Six common species that most explorers can find in their backyard. Log all six to prove you''re ready for the wild.',
   'tutorial',
   ARRAY[1, 2, 5, 6, 7, 15],
   'pathfinder',
   null,
   0),

  ('north_american_forest',
   'North American Forest',
   'Five forest dwellers across the continent. Look in dense woods, near rivers, and at the edge of fields.',
   'intermediate',
   ARRAY[3, 14, 56, 59, 67],
   null,
   'first_tracks',
   10),

  ('african_savanna',
   'African Savanna',
   'The big five icons of the savanna. Spotting them all is a lifelong ambition for most naturalists.',
   'intermediate',
   ARRAY[28, 29, 30, 31, 32],
   null,
   'first_tracks',
   20),

  ('amazon_canopy',
   'Amazon Canopy',
   'Four jewels of the South American rainforest, from the canopy down to the leaf litter.',
   'intermediate',
   ARRAY[17, 18, 23, 77],
   null,
   'first_tracks',
   30),

  ('australian_outback',
   'Australian Outback',
   'Four species you''ll only find on the lonely southern continent.',
   'intermediate',
   ARRAY[42, 43, 44, 45],
   null,
   'first_tracks',
   40),

  ('european_countryside',
   'European Countryside',
   'Five small creatures of hedgerows, farms, and woodland edges.',
   'intermediate',
   ARRAY[8, 24, 25, 26, 27],
   null,
   'first_tracks',
   50),

  ('the_polar_giant',
   'The Polar Giant',
   'A solo hunt for the largest land predator on Earth. The Arctic does not give this one up easily.',
   'legendary',
   ARRAY[12],
   'polar_giant_hunter',
   'first_tracks',
   100),

  ('the_albino',
   'The Albino',
   'Whispered about in northern woods. A pure-white deer that few have ever seen with their own eyes.',
   'legendary',
   ARRAY[10],
   'albino_witness',
   'first_tracks',
   110),

  ('the_mountain_ghost',
   'The Mountain Ghost',
   'High-altitude, near-invisible, and almost never photographed. Track it across rocky slopes above the tree line.',
   'legendary',
   ARRAY[37],
   'mountain_ghost_tracker',
   'first_tracks',
   120),

  ('the_frozen_coast',
   'The Frozen Coast',
   'Make it to Antarctica. The reward is the only flightless bird most people will ever see in the wild.',
   'legendary',
   ARRAY[11],
   'frozen_coast_witness',
   'first_tracks',
   130),

  ('the_leviathan',
   'The Leviathan',
   'The largest animal ever to have lived. You''ll need open ocean, patience, and luck.',
   'legendary',
   ARRAY[49],
   'leviathan_witness',
   'first_tracks',
   140);
